import type { HostConfig } from '@/lib/ssh'

/**
 * A real `configreport` response, for the design harness.
 *
 * GENERATED BY RUNNING THE ACTUAL VERB, not written by hand, and that is the
 * whole reason it can be trusted. `synth.ts` next door records what a
 * hand-written fixture costs: it spelled player states in uppercase, the game
 * sends lowercase, and every state filter worked in the harness and none of
 * them worked in production (#17). A harness that exercises a shape the wire
 * cannot produce is worse than no harness, because it is believed.
 *
 * So this is `tools/dispatch.sh`'s `configreport` output from the game repo,
 * run against a copy of the deployed layout, with only the absolute paths and
 * the three timestamps rewritten to what a real box would report. Every
 * convar, every group, every value string is verbatim.
 *
 * REGENERATE IT RATHER THAN EDIT IT whenever the allowlist changes, from a
 * checkout of the game repo:
 *
 *   SSH_ORIGINAL_COMMAND=configreport BR_SERVER_ROOT=<server root> \
 *     bash tools/dispatch.sh
 *
 * NOTE WHAT THE CONVARS LOOK LIKE HERE. Every `voice_*` comes back
 * `source: 'default'` with a null value, because there are no voice lines in
 * server.cfg and there are not meant to be. That is precisely the answer #150
 * spent a round failing to get, and it is the clearest illustration of why the
 * source matters as much as the value. If a future regeneration shows them
 * set, check that is really true of the box rather than convenient for a
 * screenshot.
 */
export const CONFIG_REPORT: HostConfig = {
  "ok": true,
  "at": 1786910000000,
  "serverCfg": "/opt/fivem-server-classic/server.cfg",
  "libDir": "/opt/fivem-server-classic/resources/[gamemodes]/[fivem-royale]/br_lib",
  "startedAt": 1786900000000,
  "configMtime": 1786905000000,
  "staleSinceStart": false,
  "convars": [
    {
      "name": "voice_useNativeAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_use2dAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_use3dAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_useSendingRangeOnly",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_inBitrate",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "sv_maxclients",
      "value": "48",
      "source": "server.cfg",
      "line": 37
    },
    {
      "name": "sv_hostname",
      "value": "FiveM Royale | Battle Royale",
      "source": "server.cfg",
      "line": 49
    },
    {
      "name": "sv_scriptHookAllowed",
      "value": "0",
      "source": "server.cfg",
      "line": 43
    },
    {
      "name": "onesync",
      "value": "on",
      "source": "server.cfg",
      "line": 30
    },
    {
      "name": "sv_enforceGameBuild",
      "value": "3095",
      "source": "server.cfg",
      "line": 44
    },
    {
      "name": "sv_syncTickRate",
      "value": "60",
      "source": "server.cfg",
      "line": 41
    },
    {
      "name": "sv_devMode",
      "value": "true",
      "source": "server.cfg",
      "line": 197
    },
    {
      "name": "br_devMode",
      "value": "true",
      "source": "server.cfg",
      "line": 198
    }
  ],
  "game": {
    "ok": true,
    "loadErrors": [],
    "values": [
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "maxPlayers",
        "value": "48"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "minToStart (dev)",
        "value": "1"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "minToStart (prod)",
        "value": "16"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "warmupSeconds",
        "value": "45s, cut to 15s once the lobby is full"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "endedSeconds",
        "value": "20s summary before the lobby"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "health",
        "value": "engine 100..200, display 0..100, armour cap 100"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "dbno",
        "value": "bleed 45s, revive 8s within 1.5m, revive to 30 hp"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "enabled",
        "value": "true"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "range.nearby",
        "value": "25m -- ordinary speech"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "range.squad",
        "value": "16000m -- squadmates; past the map diagonal (~14000m) means never cuts out"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "squadIsGlobal",
        "value": "true -- squads hear each other past range.nearby"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "channels",
        "value": "lobby 1000, warmup 1001, match 2000+id"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "radius0",
        "value": "3500 (floor on the computed opening radius)"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "edgeBiasMax",
        "value": "1"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "edgeHug",
        "value": "within 250m of the rim for the last 2 phases"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "total duration",
        "value": "8 phases, 21 min 55s total"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 1",
        "value": "radius 2600m, wait 120s, shrink 240s, 0.5 dps, warn 30s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 2",
        "value": "radius 1600m, wait 120s, shrink 120s, 1.25 dps, warn 30s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 3",
        "value": "radius 950m, wait 90s, shrink 90s, 1.7 dps, warn 20s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 4",
        "value": "radius 520m, wait 75s, shrink 75s, 2.2 dps, warn 20s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 5",
        "value": "radius 260m, wait 60s, shrink 60s, 2.9 dps, warn 15s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 6",
        "value": "radius 110m, wait 45s, shrink 50s, 4 dps, warn 15s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 7",
        "value": "radius 40m, wait 40s, shrink 40s, 5 dps, warn 10s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 8",
        "value": "radius 0m, wait 30s, shrink 60s, 6.7 dps, warn 10s"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "map-wide budget",
        "value": "754 POI items, summed over the POI table"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "budgetPerTier",
        "value": "tier 1 5, tier 2 8, tier 3 14"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "chestsPerTier",
        "value": "tier 1 20, tier 2 20, tier 3 24"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "filler",
        "value": "420 roadside items on the tier 1 table, 8m off the tarmac"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "chestHoldMs",
        "value": "1000ms held to open a crate"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "cellSize",
        "value": "256m streaming cell"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "propDistance",
        "value": "180m"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "pickupDistance",
        "value": "3.5m"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "slots",
        "value": "5, plus slot 0 for fists"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "weaponReserveClips",
        "value": "1"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "ammo",
        "value": "weight 74 of 100 (74%)"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "weapon",
        "value": "weight 16 of 100 (16%)"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "consumable",
        "value": "weight 6 of 100 (6%)"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "throwable",
        "value": "weight 4 of 100 (4%)"
      },
      {
        "group": "Crate contents",
        "file": "br_lib/config/loot.lua",
        "key": "2 items",
        "value": "weight 1 of 4 (25%)"
      },
      {
        "group": "Crate contents",
        "file": "br_lib/config/loot.lua",
        "key": "3 items",
        "value": "weight 2 of 4 (50%)"
      },
      {
        "group": "Crate contents",
        "file": "br_lib/config/loot.lua",
        "key": "4 items",
        "value": "weight 1 of 4 (25%)"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "currency",
        "value": "Volts"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "completion",
        "value": "15 for finishing"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "win",
        "value": "120"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "placementTop",
        "value": "70, scaled linearly by placement"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "perKill",
        "value": "10"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "perRevive",
        "value": "8"
      }
    ]
  }
}

/**
 * The same box, after somebody edited a config file and did not redeploy.
 *
 * The running server is on OLDER values than these, which is the one way this
 * report can mislead somebody — so the page has to say so loudly, and this is
 * the state that proves it does.
 */
export const CONFIG_REPORT_STALE: HostConfig = {
  "ok": true,
  "at": 1786910000000,
  "serverCfg": "/opt/fivem-server-classic/server.cfg",
  "libDir": "/opt/fivem-server-classic/resources/[gamemodes]/[fivem-royale]/br_lib",
  "startedAt": 1786900000000,
  "configMtime": 1786909000000,
  "staleSinceStart": true,
  "convars": [
    {
      "name": "voice_useNativeAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_use2dAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_use3dAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_useSendingRangeOnly",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_inBitrate",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "sv_maxclients",
      "value": "48",
      "source": "server.cfg",
      "line": 37
    },
    {
      "name": "sv_hostname",
      "value": "FiveM Royale | Battle Royale",
      "source": "server.cfg",
      "line": 49
    },
    {
      "name": "sv_scriptHookAllowed",
      "value": "0",
      "source": "server.cfg",
      "line": 43
    },
    {
      "name": "onesync",
      "value": "on",
      "source": "server.cfg",
      "line": 30
    },
    {
      "name": "sv_enforceGameBuild",
      "value": "3095",
      "source": "server.cfg",
      "line": 44
    },
    {
      "name": "sv_syncTickRate",
      "value": "60",
      "source": "server.cfg",
      "line": 41
    },
    {
      "name": "sv_devMode",
      "value": "true",
      "source": "server.cfg",
      "line": 197
    },
    {
      "name": "br_devMode",
      "value": "true",
      "source": "server.cfg",
      "line": 198
    }
  ],
  "game": {
    "ok": true,
    "loadErrors": [],
    "values": [
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "maxPlayers",
        "value": "48"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "minToStart (dev)",
        "value": "1"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "minToStart (prod)",
        "value": "16"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "warmupSeconds",
        "value": "45s, cut to 15s once the lobby is full"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "endedSeconds",
        "value": "20s summary before the lobby"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "health",
        "value": "engine 100..200, display 0..100, armour cap 100"
      },
      {
        "group": "Match",
        "file": "br_lib/config/match.lua",
        "key": "dbno",
        "value": "bleed 45s, revive 8s within 1.5m, revive to 30 hp"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "enabled",
        "value": "true"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "range.nearby",
        "value": "25m -- ordinary speech"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "range.squad",
        "value": "16000m -- squadmates; past the map diagonal (~14000m) means never cuts out"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "squadIsGlobal",
        "value": "true -- squads hear each other past range.nearby"
      },
      {
        "group": "Voice (gamemode)",
        "file": "br_lib/config/match.lua",
        "key": "channels",
        "value": "lobby 1000, warmup 1001, match 2000+id"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "radius0",
        "value": "3500 (floor on the computed opening radius)"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "edgeBiasMax",
        "value": "1"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "edgeHug",
        "value": "within 250m of the rim for the last 2 phases"
      },
      {
        "group": "Storm",
        "file": "br_lib/config/storm.lua",
        "key": "total duration",
        "value": "8 phases, 21 min 55s total"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 1",
        "value": "radius 2600m, wait 120s, shrink 240s, 0.5 dps, warn 30s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 2",
        "value": "radius 1600m, wait 120s, shrink 120s, 1.25 dps, warn 30s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 3",
        "value": "radius 950m, wait 90s, shrink 90s, 1.7 dps, warn 20s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 4",
        "value": "radius 520m, wait 75s, shrink 75s, 2.2 dps, warn 20s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 5",
        "value": "radius 260m, wait 60s, shrink 60s, 2.9 dps, warn 15s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 6",
        "value": "radius 110m, wait 45s, shrink 50s, 4 dps, warn 15s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 7",
        "value": "radius 40m, wait 40s, shrink 40s, 5 dps, warn 10s"
      },
      {
        "group": "Storm phases",
        "file": "br_lib/config/storm.lua",
        "key": "phase 8",
        "value": "radius 0m, wait 30s, shrink 60s, 6.7 dps, warn 10s"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "map-wide budget",
        "value": "754 POI items, summed over the POI table"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "budgetPerTier",
        "value": "tier 1 5, tier 2 8, tier 3 14"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "chestsPerTier",
        "value": "tier 1 20, tier 2 20, tier 3 24"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "filler",
        "value": "420 roadside items on the tier 1 table, 8m off the tarmac"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "chestHoldMs",
        "value": "1000ms held to open a crate"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "cellSize",
        "value": "256m streaming cell"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "propDistance",
        "value": "180m"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "pickupDistance",
        "value": "3.5m"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "slots",
        "value": "5, plus slot 0 for fists"
      },
      {
        "group": "Loot",
        "file": "br_lib/config/loot.lua",
        "key": "weaponReserveClips",
        "value": "1"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "ammo",
        "value": "weight 74 of 100 (74%)"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "weapon",
        "value": "weight 16 of 100 (16%)"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "consumable",
        "value": "weight 6 of 100 (6%)"
      },
      {
        "group": "Floor loot weights",
        "file": "br_lib/config/loot.lua",
        "key": "throwable",
        "value": "weight 4 of 100 (4%)"
      },
      {
        "group": "Crate contents",
        "file": "br_lib/config/loot.lua",
        "key": "2 items",
        "value": "weight 1 of 4 (25%)"
      },
      {
        "group": "Crate contents",
        "file": "br_lib/config/loot.lua",
        "key": "3 items",
        "value": "weight 2 of 4 (50%)"
      },
      {
        "group": "Crate contents",
        "file": "br_lib/config/loot.lua",
        "key": "4 items",
        "value": "weight 1 of 4 (25%)"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "currency",
        "value": "Volts"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "completion",
        "value": "15 for finishing"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "win",
        "value": "120"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "placementTop",
        "value": "70, scaled linearly by placement"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "perKill",
        "value": "10"
      },
      {
        "group": "Payout",
        "file": "br_lib/config/market.lua",
        "key": "perRevive",
        "value": "8"
      }
    ]
  }
}

/**
 * Convars readable, gamemode half not.
 *
 * A REAL AND UNDRAMATIC FAILURE. The game host reads convars with shell
 * builtins, but the gamemode values need a Lua interpreter and nothing
 * guarantees one is installed. Half a report is worth showing, and the reason
 * is worth naming: "install lua5.4" is something an operator can act on, where
 * a silently empty section is something they file a bug about.
 *
 * FXServer is also stopped here (`startedAt: 0`), which is why staleness is
 * not claimed — with no process there is no "since it started", and saying
 * "your edits are not live" would be a strange way to report "nothing is".
 */
export const CONFIG_REPORT_NO_LUA: HostConfig = {
  "ok": true,
  "at": 1786910000000,
  "serverCfg": "/opt/fivem-server-classic/server.cfg",
  "libDir": "/opt/fivem-server-classic/resources/[gamemodes]/[fivem-royale]/br_lib",
  "startedAt": 0,
  "configMtime": 1786905000000,
  "staleSinceStart": false,
  "convars": [
    {
      "name": "voice_useNativeAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_use2dAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_use3dAudio",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_useSendingRangeOnly",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "voice_inBitrate",
      "value": null,
      "source": "default",
      "line": 0
    },
    {
      "name": "sv_maxclients",
      "value": "48",
      "source": "server.cfg",
      "line": 37
    },
    {
      "name": "sv_hostname",
      "value": "FiveM Royale | Battle Royale",
      "source": "server.cfg",
      "line": 49
    },
    {
      "name": "sv_scriptHookAllowed",
      "value": "0",
      "source": "server.cfg",
      "line": 43
    },
    {
      "name": "onesync",
      "value": "on",
      "source": "server.cfg",
      "line": 30
    },
    {
      "name": "sv_enforceGameBuild",
      "value": "3095",
      "source": "server.cfg",
      "line": 44
    },
    {
      "name": "sv_syncTickRate",
      "value": "60",
      "source": "server.cfg",
      "line": 41
    },
    {
      "name": "sv_devMode",
      "value": "true",
      "source": "server.cfg",
      "line": 197
    },
    {
      "name": "br_devMode",
      "value": "true",
      "source": "server.cfg",
      "line": 198
    }
  ],
  "game": {
    "ok": false,
    "loadErrors": [
      "no lua interpreter on this host -- install one with: sudo apt install -y lua5.4"
    ],
    "values": []
  }
}
